lobsters/config/routes.rb
Lobsters::Application.routes.draw do
  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/404" => "home#four_oh_four", :via => :all

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user", :format => /html|json|rss/
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"
    get "/saved" => "home#saved", :format => /html|rss|json/
    get "/saved/page/:page" => "home#saved"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"
    get "/login/2fa" => "login#twofa"
    post "/login/2fa_verify" => "login#twofa_verify", :as => "twofa_login"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss|json/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
      post "save"
      post "unsave"
      get "suggest"
      post "suggest", :action => "submit_suggestions"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"
    post "/stories/check_url_dupe" => "stories#check_url_dupe"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"

        post "dragon"
        post "undragon"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent", :format => /html|json/
    get "/messages" => "messages#index", :format => /html|json/
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/c/:id" => "comments#redirect_from_short_id"
    get "/c/:id.json" => "comments#show_short_id", :format => "json"

    # deprecated
    get "/s/:story_id/:title/comments/:id" => "comments#redirect_from_short_id"

    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/u" => "users#tree"
    get "/u/:username" => "users#show", :as => "user", :format => /html|json/

    get "/avatars/:username_size.png" => "avatars#show"
    post "/avatars/expire" => "avatars#expire"

    post "/users/:username/ban" => "users#ban", :as => "user_ban"
    post "/users/:username/unban" => "users#unban", :as => "user_unban"
    post "/users/:username/disable_invitation" => "users#disable_invitation", :as => "user_disable_invite"
    post "/users/:username/enable_invitation" => "users#enable_invitation", :as => "user_enable_invite"

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"
    get "/settings/2fa" => "settings#twofa", :as => "twofa"
    post "/settings/2fa_auth" => "settings#twofa_auth", :as => "twofa_auth"
    get "/settings/2fa_enroll" => "settings#twofa_enroll",
      :as => "twofa_enroll"
    get "/settings/2fa_verify" => "settings#twofa_verify",
      :as => "twofa_verify"
    post "/settings/2fa_update" => "settings#twofa_update",
      :as => "twofa_update"

    post "/settings/pushover_auth" => "settings#pushover_auth"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    get "/settings/github_auth" => "settings#github_auth"
    get "/settings/github_callback" => "settings#github_callback"
    post "/settings/github_disconnect" => "settings#github_disconnect"
    get "/settings/twitter_auth" => "settings#twitter_auth"
    get "/settings/twitter_callback" => "settings#twitter_callback"
    post "/settings/twitter_disconnect" => "settings#twitter_disconnect"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    get "/tags" => "tags#index"
    get "/tags.json" => "tags#index", :format => "json"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/hats" => "hats#index"
    get "/hats/build_request" => "hats#build_request",
      :as => "request_hat"
    post "/hats/create_request" => "hats#create_request",
      :as => "create_hat_request"
    get "/hats/requests" => "hats#requests_index"
    post "/hats/approve_request/:id" => "hats#approve_request",
      :as => "approve_hat_request"
    post "/hats/reject_request/:id" => "hats#reject_request",
      :as => "reject_hat_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"
    get "/moderators" => "users#tree", :moderators => true

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"
    get "/chat" => "home#chat"

    get "/hat/:hat" => "hat#show"
  end
end

lobsters/app/models/hat.rb
class Hat < ActiveRecord::Base
  belongs_to :user
  belongs_to :granted_by_user,
    :class_name => "User"

  validates :user, :hat, :presence => true
  validates :granted_by_user, :presence => true

  after_create :log_moderation

  def doff_by_user_with_reason(user, reason)
    m = Moderation.new
    m.user_id = self.user_id
    m.moderator_user_id = user.id
    m.action = "Doffed hat \"#{self.hat}\": #{reason}"
    m.save!

    self.doffed_at = Time.now
    self.save!
  end

  def destroy_by_user_with_reason(user, reason)
    m = Moderation.new
    m.user_id = self.user_id
    m.moderator_user_id = user.id
    m.action = "Revoked hat \"#{self.hat}\": #{reason}"
    m.save!

    self.destroy
  end

  def to_html_label
    hl = (self.link.present? && self.link.match(/^https?:\/\//))

    h = "<span class=\"hat " <<
      "hat_#{self.hat.gsub(/[^A-Za-z0-9]/, "_").downcase}\" " <<
      "title=\"Granted by " << "#{self.granted_by_user.username} on " <<
      "#{self.created_at.strftime("%Y-%m-%d")}"

    if !hl && self.link.present?
      h << " - #{ERB::Util.html_escape(self.link)}"
    end

    h << "\">" <<
      "<span class=\"crown\">"

    if hl
      h << "<a href=\"#{ERB::Util.html_escape(self.link)}\" target=\"_blank\">"
    end

    h << ERB::Util.html_escape(self.hat)

    if hl
      h << "</a>"
    end

    h << "</span></span>"

    h.html_safe
  end

  def log_moderation
    m = Moderation.new
    m.created_at = self.created_at
    m.user_id = self.user_id
    m.moderator_user_id = self.granted_by_user_id
    m.action = "Granted hat \"#{self.hat}\"" + (self.link.present? ?
      " (#{self.link})" : "")
    m.save
  end
end

lobsters/app/controllers/hat_controller.rb
class HatController < ApplicationController
    def show
    end
end

lobsters/app/controllers/hats_controller.rb
include RailsOpentracer
require 'hat_request_representer'

class HatsController < ApplicationController
  before_action :require_logged_in_user, :except => [ :index ]
  before_action :require_logged_in_moderator,
    :except => [ :build_request, :index, :create_request ]

  def build_request
    @title = "Request a Hat"

    @hat_request = HatRequest.new
  end

  def index
    @title = "Hats"

    @hat_groups = {}

    Hat.all.includes(:user).each do |h|
      @hat_groups[h.hat] ||= []
      @hat_groups[h.hat].push h
    end
  end

  def create_request
    subject = url_for(controller: "users", action: "show", username: @user.username)
    object = url_for(controller: "hat", action: "show", hat: params[:hat_request][:hat])
    text_evidence = {:text => params[:hat_request][:comment]}
    linked_evidence = {:link => params[:hat_request][:link]}

    request = HatRequestNew.new(
      :subject => subject,
      :object => object,
      :evidence => [text_evidence, linked_evidence])

    with_span 'request-post' do
      request.post(uri: Lobsters::Application.config.request_service_uri, as: "application/json")
    end

    return redirect_to "/hats"
  end
      
  def requests_index
    @title = "Hat Requests"
    @hat_requests = HatRequest.all.includes(:user)
  end

  def approve_request
    @hat_request = HatRequest.find(params[:id])
    @hat_request.update_attributes!(params.require(:hat_request).
      permit(:hat, :link))
    @hat_request.approve_by_user!(@user)

    flash[:success] = "Successfully approved hat request."

    return redirect_to "/hats/requests"
  end

  def reject_request
    @hat_request = HatRequest.find(params[:id])
    @hat_request.reject_by_user_for_reason!(@user,
      params[:hat_request][:rejection_comment])

    flash[:success] = "Successfully rejected hat request."

    return redirect_to "/hats/requests"
  end
end

lobsters/app/views/hats/build_request.html.erb
<div class="box wide">
  <div class="legend">
    Request a Hat
  </div>

  <p>
  A hat is a formal, verified, way of posting a comment while speaking for a
  project, organization, or company.  Each user may have multiple hats, one of
  which may be worn at any time when posting a comment or sending a private
  message.
  </p>
  <p>
  Hats are intended for core project developers and company employees that are
  authorized to make comments on behalf of those organizations, and are usually
  reserved for notable projects and organizations.  Hats are not intended to
  list every contribution a person has made to any software project.
  </p>
  <p>
  Hats will not be authorized for occasional contributors to projects,
  developers of projects which are not widely known, past employees of
  companies, or other situations where it cannot be verified that one is
  authorized to represent that organization.  In general, unless one has an
  e-mail address at a company domain or have commit access to a project, a hat
  will not be authorized.
  </p>
  <p>
  To request a hat for your account, provide a short description of the hat
  (e.g., "OpenBSD Developer"), a public link that will be shown when hovering
  over the hat that users can see, such as your e-mail address at that project
  or company, or a link to a company website showing your employment, and
  private comments that will be seen only by moderators during approval.
  </p>
  <p>
  Once your hat is requested, a moderator will verify your request by e-mailing
  the address you submitted as the link, or doing some other manual
  verification of project association.
  </p>

  <%= form_for @hat_request, :url => create_hat_request_path do |f| %>
    <p>
    <%= f.label :hat, "Hat:" %>
    <%= f.text_field :hat, :size => 20,
      :placeholder => "XYZ Project Member" %>
    <br />

    <%= f.label :link, "Link:" %>
    <%= f.text_field :link, :size => 50,
      :placeholder => "user@project.org, or a URL to an employment page" %>
    <br />

    <%= f.label :comment, "Comment:" %>
    <%= f.text_area :comment, :rows => 4,
      :placeholder => "Will only be shown to moderators during approval" %>
    </p>

    <p>
    <%= submit_tag "Request Hat" %>
    </p>
  <% end %>
</div>

lobsters/app/views/hats/index.html.erb
<div class="box wide">
  <% if @user %>
    <div class="legend right">
      <a href="<%= request_hat_url %>">Request Hat</a>
    </div>
  <% end %>
  <div class="legend">
    Hats
  </div>

  <p>
  A hat is a formal, verified, way of posting a comment while speaking for a
  project, organization, or company.  Each user may have multiple hats, one of
  which may be selected to be worn when posting a comment or sending a private
  message.
  </p>

  <table class="data" width="100%" cellspacing=0>
  <tr>
    <th style="width: 130px;">User</th>
    <th>Hat</th>
    <th>Link</th>
  </tr>
  <% bit = 0 %>
  <% @hat_groups.keys.sort_by{|a| a.downcase }.each do |hg| %>
    <% @hat_groups[hg].sort_by{|hh| hh.user.username.downcase }.each do |hh| %>
      <tr class="row<%= bit %>">
        <td><a href="/u/<%= hh.user.username %>"><%= hh.user.username
          %></a></td>
        <td><%= hh.to_html_label %></td>
        <td>
          <% if hh.link.to_s.match(/^http/) %>
            <a href="<%= hh.link %>" rel="nofollow"><%= hh.link %></a>
          <% elsif hh.link.blank? %>
            <span class="na">None</span>
          <% else %>
            <%= hh.link %>
          <% end %>
          <% if hh.doffed_at? %>
            doffed <%= time_ago_in_words_label(hh.doffed_at) %>
          <% end %>
        </td>
      </tr>
      <% bit = (bit == 1 ? 0 : 1) %>
    <% end %>
  <% end %>
  </table>
</div>

lobsters/app/views/hats/requests_index.html.erb
<div class="box wide">
  <div class="legend">
    Requested Hats
  </div>

  <% if @hat_requests.count == 0 %>
    No hat requests.
  <% else %>
    <% @hat_requests.each_with_index do |hr,x| %>
      <% if x > 0 %>
        <hr>
      <% end %>

      <%= form_for hr, :url => approve_hat_request_url(:id => hr),
      :method => :post do |f| %>
        <p>
        <div class="boxline">
          <%= f.label :user_id, "User:", :class => "required" %>
          <a href="/u/<%= hr.user.username %>"><%= hr.user.username %></a>
        </div>

        <div class="boxline">
          <%= f.label :hat, "Hat:", :class => "required" %>
          <%= f.text_field "hat", :size => 25 %>
        </div>

        <div class="boxline">
          <%= f.label :link, "Link:", :class => "required" %>
          <%= f.text_field "link", :size => 75 %>
          <% if hr.link.to_s.match(/^http/) %>
            <br>
            <%= f.label :link, "Link:", :class => "required" %>
            <a href="<%= hr.link %>" rel="nofollow"><%= hr.link %></a>
          <% end %>
        </div>

        <div class="boxline">
          <%= f.label :link, "Comment:", :class => "required" %>
          <div class="d">
            <%= raw(h(hr.comment.to_s).gsub(/\n/, "<br>")) %>
          </div>
        </div>

        <p style="clear: both;">
        <%= submit_tag "Approve Hat Request" %>
        </p>
      <% end %>
      <p>
      or
      </p>
      <%= form_for hr, :url => reject_hat_request_url(:id => hr),
      :method => :post do |f| %>
        <div class="boxline">
          <%= f.label :link, "Reason:", :class => "required" %>
          <%= f.text_area :rejection_comment, :rows => 4 %>
        </div>
        <p>
        <%= submit_tag "Reject Hat Request" %>
        </p>
      <% end %>
    <% end %>
  <% end %>
</div>